Repository apache/pulsar-client-python, pull requests merged in 2023-02, with the labels that each got.

#83 Add support for Python 3.11
  .github/workflows/ci-build-release-wheels.yaml
  .github/workflows/ci-pr-validation.yaml
  setup.py
Labels: enhancement

#87 Fixed deadlock in producer.send_async
  src/consumer.cc
  src/producer.cc
  tests/pulsar_test.py
Labels: bug

#91 Update the release process for versioning
  RELEASE.md
Labels: documentation

#93 #66: Add Human-readable description of MessageId object
  src/message.cc
Labels: enhancement

#95 Issue #37 : Allow passing pulsar.MessageId instance to create_reader()
  pulsar/__init__.py
Labels: enhancement
